#cloud-config
fqdn: ${hostname} 
chpasswd:
    list: |
      ubuntu:${vm_password}
    expire: false
users:
  - default 
  - name: ubuntu
    gecos: Local
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
    - gh:jacopen
    - gh:TakumaNakagame
    - gh:capsmalt
    - gh:Gaku-Kunimi
    - gh:inductor
    - gh:tanayan299
    - gh:onarada
    - gh:ijokarumawak
    - gh:tkc66-buzz
    - gh:morimorikun51
system_info: 
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
ssh_pwauth: yes
random_seed:
    file: /dev/urandom
    command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
    command_required: true
package_upgrade: true
packages:
  - curl
  - vim
  - git
  - unzip
  - gnupg
  - lsb-release
  - ca-certificates
  - dstat
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - sleep 3 && git clone https://github.com/cloudnativedaysjp/broadcast-config /home/ubuntu/broadcast-config
  - cd /home/ubuntu/broadcast-config/nextcloud && sudo docker compose up -d
  - |
    cat - << EOF | sudo tee /etc/netplan/51-secondary-nic.yaml
    network:
        ethernets:
            ens4:
                dhcp4: false
                addresses: [${secondary_ip}/24]
        version: 2
    EOF
  - sudo netplan apply
  - |
    curl -X POST --data-urlencode "payload={\"channel\": \"#broadcast\", \"username\": \"EMTEC\", \"text\": \"VM: ${hostname}が起動しました。\"}" ${broadcast_webhook_url}
