#cloud-config
fqdn: ${hostname} 
chpasswd:
    list: |
      ubuntu:${vm_password}
    expire: false
users:
  - default 
  - name: ubuntu
    gecos: Local
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
    - gh:jacopen
    - gh:TakumaNakagame
    - gh:mikiT
    - gh:MasayaAoyama
    - gh:TatsukiMinami
    - gh:ystkfujii
    - gh:takei-ryuichi
    - gh:Himalayan-wildcat
    - gh:Drumato
    - gh:hayama17
    - gh:tsukaman
    - gh:yuriacats
    - gh:sleepyfox97
    - gh:yoshihiro-shu

system_info: 
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
ssh_pwauth: yes
random_seed:
    file: /dev/urandom
    command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
    command_required: true
package_upgrade: true
packages:
  - curl
  - vim
  - git
  - unzip
  - gnupg
  - lsb-release
  - ca-certificates
  - dstat
runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
