#cloud-config
fqdn: ${hostname} 
chpasswd:
    list: |
      ubuntu:${vm_password}
    expire: false
users:
  - default 
  - name: ubuntu
    gecos: Local
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
    - gh:jacopen
    - gh:TakumaNakagame
    - gh:capsmalt
    - gh:Gaku-Kunimi
    - gh:tanayan299
    - gh:onarada
    - gh:ijokarumawak
    - gh:tkc66-buzz
    - gh:morimorikun51
system_info: 
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
ssh_pwauth: yes
random_seed:
    file: /dev/urandom
    command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
    command_required: true
package_upgrade: true
packages:
  - curl
  - vim
  - git
  - unzip
  - ubuntu-drivers-common
  - ocl-icd-libopencl1
  - opencl-headers
  - clinfo
  - ffmpeg
  - net-tools
  - software-properties-common
  - dstat
  - iftop
runcmd:
  - curl -sSL https://raw.githubusercontent.com/cloudnativedaysjp/terraform/main/scripts/install-docker.sh | sh -
  - |
    cat - << EOF | sudo tee /etc/netplan/51-secondary-nic.yaml
    network:
        ethernets:
            ens4:
                dhcp4: false
                addresses: [${secondary_ip}/24]
        version: 2
    EOF
  - sudo netplan apply
  - sleep 3 && git clone https://github.com/cloudnativedaysjp/broadcast.git /home/ubuntu/broadcast
  - cd /home/ubuntu/broadcast/nginx-rtmp && sudo docker compose up -d
  - cd /home/ubuntu/broadcast/srs && sudo docker compose up -d
